import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from '../src/lib/server/db/schema';
import { existsSync, mkdirSync, unlinkSync } from 'fs';
import { join } from 'path';

const DB_PATH = join(process.cwd(), 'data', 'sales_advisor.db');
const dataDir = join(process.cwd(), 'data');
if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });

// Delete existing DB file before seeding (fresh start)
if (existsSync(DB_PATH)) unlinkSync(DB_PATH);

const sqlite = new Database(DB_PATH);
sqlite.pragma('journal_mode = WAL');
sqlite.pragma('foreign_keys = ON');
const db = drizzle(sqlite, { schema });

// Run migrations to create tables
migrate(db, { migrationsFolder: './drizzle/migrations' });

function id(prefix: string, n: number | string) { return `${prefix}-${n}`; }

async function seed() {
  console.log('Seeding database for PT Eonchemicals Putra...');

  // ── Industries ──────────────────────────────────────────────────────────────
  const industries = [
    { id: 'ind-maritime', name: 'Maritime', code: 'MARITIME', description: 'Shipping, ports, shipyards, offshore oil & gas, ferry operations across Indonesian archipelago' },
    { id: 'ind-mining', name: 'Mining', code: 'MINING', description: 'Coal mining, mineral mining, open-pit operations, nickel smelting, copper/gold processing' },
    { id: 'ind-general', name: 'General Industrial', code: 'GENERAL', description: 'Steel manufacturing, palm oil processing, food & beverage, cement, petrochemical, automotive' },
  ];
  for (const r of industries) await db.insert(schema.industries).values(r).onConflictDoNothing();

  // ── Product Families ────────────────────────────────────────────────────────
  const families = [
    { id: 'fam-boiler',   name: 'Boiler Chemical',          code: 'BOILER',   description: 'Scale inhibitors, oxygen scavengers, pH adjusters, and descalers for boiler systems' },
    { id: 'fam-cleaning', name: 'Cleaning Chemical',        code: 'CLEANING', description: 'Degreasers, solvents, general-purpose and specialty cleaners' },
    { id: 'fam-coating',  name: 'Coating',                  code: 'COATING',  description: 'Anti-rust epoxy coatings, rust converters, pipe protection coatings' },
    { id: 'fam-cooling',  name: 'Cooling Tower Chemical',   code: 'COOLING',  description: 'Biocides, algae control, scale inhibitors for cooling water systems' },
    { id: 'fam-lube',     name: 'Lubricant',                code: 'LUBRICANT', description: 'Wire rope lubricants, greases, specialty industrial lubricants' },
    { id: 'fam-oilspill', name: 'Oil Spill Dispersant',     code: 'OILSPILL', description: 'Dispersants, absorbents, spill response kits for marine and industrial use' },
    { id: 'fam-fire',     name: 'Fire Safety',              code: 'FIRE',     description: 'Firefighting foam concentrates for marine and industrial applications' },
    { id: 'fam-fuel',     name: 'Fuel Additive',            code: 'FUEL',     description: 'Diesel performance enhancers, fuel stabilizers, combustion improvers' },
  ];
  for (const r of families) await db.insert(schema.productFamilies).values(r).onConflictDoNothing();

  // ── Products (50 products) ─────────────────────────────────────────────────
  const products = [
    // Boiler Chemical (8)
    { id: 'p-b01', familyId: 'fam-boiler', name: 'EonScale B 5155', sku: 'ESB-5155', description: 'High-performance boiler scale inhibitor for medium-pressure systems', unitPrice: 185000, uom: 'kg', primaryUseCase: 'boiler scale prevention medium pressure steam system', keyBenefits: JSON.stringify(['Prevents calcium/magnesium scale', 'Effective up to 60 bar', 'Reduces blowdown frequency']), typicalVolumeKg: 500 },
    { id: 'p-b02', familyId: 'fam-boiler', name: 'EonAlkalox B 1414', sku: 'EAB-1414', description: 'Alkalinity booster and pH adjuster for boiler feedwater', unitPrice: 120000, uom: 'kg', primaryUseCase: 'boiler pH control alkalinity feedwater treatment', keyBenefits: JSON.stringify(['Maintains optimal pH 10.5-11.5', 'Prevents acidic corrosion', 'Compatible with phosphate programs']), typicalVolumeKg: 400 },
    { id: 'p-b03', familyId: 'fam-boiler', name: 'EonDescaler B 2550', sku: 'EDB-2550', description: 'Concentrated acid descaler for boiler tubes and drums', unitPrice: 95000, uom: 'kg', primaryUseCase: 'boiler descaling tube cleaning maintenance shutdown', keyBenefits: JSON.stringify(['Inhibited formula safe for steel', 'Removes silica and calcium scale', 'Fast-acting — 4-6 hour treatment']), typicalVolumeKg: 800 },
    { id: 'p-b04', familyId: 'fam-boiler', name: 'EonDescaler 505', sku: 'ED-505', description: 'General-purpose descaler for heat exchangers and boilers', unitPrice: 78000, uom: 'kg', primaryUseCase: 'heat exchanger descaling general boiler cleaning', keyBenefits: JSON.stringify(['Safe on copper and steel', 'Biodegradable', 'Low fume formulation']), typicalVolumeKg: 600 },
    { id: 'p-b05', familyId: 'fam-boiler', name: 'EonOxy B 3200', sku: 'EOB-3200', description: 'Catalyzed sodium sulphite oxygen scavenger for boiler feedwater', unitPrice: 145000, uom: 'kg', primaryUseCase: 'boiler oxygen scavenger feedwater pitting corrosion prevention', keyBenefits: JSON.stringify(['Rapid oxygen removal', 'Prevents pitting corrosion', 'Suitable for high-pressure boilers']), typicalVolumeKg: 300 },
    { id: 'p-b06', familyId: 'fam-boiler', name: 'EonCond B 4100', sku: 'ECB-4100', description: 'Condensate line treatment for pH control and corrosion prevention', unitPrice: 210000, uom: 'kg', primaryUseCase: 'condensate return line corrosion pH control steam', keyBenefits: JSON.stringify(['Neutralizing amine blend', 'Protects condensate piping', 'Reduces iron levels in return']), typicalVolumeKg: 250 },
    { id: 'p-b07', familyId: 'fam-boiler', name: 'EonPhos B 2800', sku: 'EPB-2800', description: 'Phosphate-based sludge conditioner for boiler drum treatment', unitPrice: 110000, uom: 'kg', primaryUseCase: 'boiler sludge conditioning drum treatment phosphate', keyBenefits: JSON.stringify(['Conditions sludge for easy blowdown', 'Prevents hard scale adherence', 'Works in high-hardness feedwater']), typicalVolumeKg: 350 },
    { id: 'p-b08', familyId: 'fam-boiler', name: 'EonGuard B 6000', sku: 'EGB-6000', description: 'All-in-one boiler treatment for low-pressure fire tube boilers', unitPrice: 165000, uom: 'kg', primaryUseCase: 'fire tube boiler all-in-one treatment palm oil mill', keyBenefits: JSON.stringify(['Single-product simplicity', 'Scale + corrosion + sludge control', 'Ideal for palm oil mill boilers']), typicalVolumeKg: 700 },

    // Cleaning Chemical (7)
    { id: 'p-cl01', familyId: 'fam-cleaning', name: 'EonClean 500', sku: 'EC-500', description: 'Heavy-duty alkaline degreaser for marine and industrial surfaces', unitPrice: 68000, uom: 'liter', primaryUseCase: 'degreasing engine room deck equipment marine industrial', keyBenefits: JSON.stringify(['Cuts through heavy oil and grease', 'Water-based low VOC', 'Safe on painted surfaces']), typicalVolumeKg: 2000 },
    { id: 'p-cl02', familyId: 'fam-cleaning', name: 'EonSolv 135', sku: 'ES-135', description: 'Solvent-based cleaner for precision parts and electrical equipment', unitPrice: 125000, uom: 'liter', primaryUseCase: 'solvent cleaning precision parts electrical degreasing', keyBenefits: JSON.stringify(['Fast evaporation', 'Leaves no residue', 'Non-conductive']), typicalVolumeKg: 500 },
    { id: 'p-cl03', familyId: 'fam-cleaning', name: 'EonMotor 100', sku: 'EM-100', description: 'Engine cleaner and degreaser for marine and automotive engines', unitPrice: 55000, uom: 'liter', primaryUseCase: 'engine cleaning marine automotive diesel motor degreaser', keyBenefits: JSON.stringify(['Penetrates carbon deposits', 'Safe for rubber seals', 'Rinses clean with water']), typicalVolumeKg: 1500 },
    { id: 'p-cl04', familyId: 'fam-cleaning', name: 'EonWash', sku: 'EW-001', description: 'General-purpose industrial wash for floors, tanks, and vessels', unitPrice: 45000, uom: 'liter', primaryUseCase: 'general wash tank cleaning floor industrial vessel', keyBenefits: JSON.stringify(['Versatile all-surface cleaner', 'High dilution ratio', 'Pleasant scent']), typicalVolumeKg: 3000 },
    { id: 'p-cl05', familyId: 'fam-cleaning', name: 'EonMar CL 200', sku: 'EMC-200', description: 'Marine-grade cargo hold cleaner for bulk carriers', unitPrice: 88000, uom: 'liter', primaryUseCase: 'cargo hold cleaning marine bulk carrier coal grain', keyBenefits: JSON.stringify(['Meets P&I club requirements', 'Effective on coal residue', 'Fast turnaround cleaning']), typicalVolumeKg: 1200 },
    { id: 'p-cl06', familyId: 'fam-cleaning', name: 'EonBright 310', sku: 'EB-310', description: 'Acid-based brightener and passivator for stainless steel surfaces', unitPrice: 135000, uom: 'liter', primaryUseCase: 'stainless steel brightening passivation food beverage', keyBenefits: JSON.stringify(['Restores bright finish', 'Passivates for corrosion resistance', 'Food-grade approved']), typicalVolumeKg: 300 },
    { id: 'p-cl07', familyId: 'fam-cleaning', name: 'EonTank 450', sku: 'ET-450', description: 'Tank cleaning chemical for fuel oil and crude oil tanks', unitPrice: 98000, uom: 'liter', primaryUseCase: 'tank cleaning fuel oil crude marine shipyard', keyBenefits: JSON.stringify(['Emulsifies heavy fuel residue', 'Reduces gas-free time', 'IMO-compliant formulation']), typicalVolumeKg: 800 },

    // Coating (7)
    { id: 'p-co01', familyId: 'fam-coating', name: 'EonCoat 551', sku: 'ECO-551', description: 'Two-component anti-rust epoxy coating for marine structures', unitPrice: 285000, uom: 'kg', primaryUseCase: 'anti-rust epoxy marine structure ship hull coating', keyBenefits: JSON.stringify(['Excellent saltwater resistance', 'Tropical humidity cure', '10-year protection in marine C5 environment']), typicalVolumeKg: 500 },
    { id: 'p-co02', familyId: 'fam-coating', name: 'EonCoat 470', sku: 'ECO-470', description: 'Single-component rust converter and primer for corroded steel', unitPrice: 195000, uom: 'kg', primaryUseCase: 'rust converter primer corroded steel rehabilitation', keyBenefits: JSON.stringify(['Converts rust to stable primer', 'Minimal surface prep needed', 'Overcoatable within 4 hours']), typicalVolumeKg: 400 },
    { id: 'p-co03', familyId: 'fam-coating', name: 'EonVert 344', sku: 'EV-344', description: 'High-build epoxy coating for vertical and overhead surfaces', unitPrice: 320000, uom: 'kg', primaryUseCase: 'vertical overhead coating epoxy thick film ship hull', keyBenefits: JSON.stringify(['Non-sag formula', 'High build — 300 micron single coat', 'Excellent edge retention']), typicalVolumeKg: 350 },
    { id: 'p-co04', familyId: 'fam-coating', name: 'EonFilm 240', sku: 'EF-240', description: 'Thin-film zinc-rich primer for new steel construction', unitPrice: 265000, uom: 'kg', primaryUseCase: 'zinc primer new construction steel fabrication shipyard', keyBenefits: JSON.stringify(['Weldable zinc-rich primer', '85% zinc content', 'Fast dry for production speed']), typicalVolumeKg: 600 },
    { id: 'p-co05', familyId: 'fam-coating', name: 'EonFilm 300', sku: 'EF-300', description: 'Anti-fouling paint for ship hulls and underwater structures', unitPrice: 380000, uom: 'kg', primaryUseCase: 'anti-fouling ship hull underwater marine biofouling', keyBenefits: JSON.stringify(['TBT-free IMO compliant', 'Self-polishing technology', '36-month service interval']), typicalVolumeKg: 800 },
    { id: 'p-co06', familyId: 'fam-coating', name: 'EonPipe 620', sku: 'EP-620', description: 'Internal pipe coating for water and slurry pipelines', unitPrice: 245000, uom: 'kg', primaryUseCase: 'internal pipe coating water slurry mining pipeline protection', keyBenefits: JSON.stringify(['Abrasion resistant for slurry', 'Reduces friction loss', 'Extends pipe life 3x']), typicalVolumeKg: 1000 },
    { id: 'p-co07', familyId: 'fam-coating', name: 'EonCor 780', sku: 'ECR-780', description: 'Coal tar epoxy coating for buried pipelines and marine piling', unitPrice: 175000, uom: 'kg', primaryUseCase: 'coal tar epoxy buried pipeline marine piling waterfront', keyBenefits: JSON.stringify(['Outstanding water resistance', 'Chemical resistant', 'Proven 20+ year track record in Indonesia']), typicalVolumeKg: 900 },

    // Cooling Tower Chemical (7)
    { id: 'p-ct01', familyId: 'fam-cooling', name: 'EonBac GEO 9910', sku: 'EBG-9910', description: 'Non-oxidizing biocide for cooling tower and process water systems', unitPrice: 165000, uom: 'kg', primaryUseCase: 'cooling tower biocide non-oxidizing bacteria algae control', keyBenefits: JSON.stringify(['Broad-spectrum kill', 'Effective against Legionella', 'Low corrosivity to system metals']), typicalVolumeKg: 400 },
    { id: 'p-ct02', familyId: 'fam-cooling', name: 'EonLine AG 5770', sku: 'ELA-5770', description: 'Algaecide and biofilm dispersant for open cooling systems', unitPrice: 135000, uom: 'kg', primaryUseCase: 'algae control biofilm cooling tower open system tropical', keyBenefits: JSON.stringify(['Controls tropical algae strains', 'Disperses existing biofilm', 'UV stable formulation']), typicalVolumeKg: 500 },
    { id: 'p-ct03', familyId: 'fam-cooling', name: 'EonScale T 2511', sku: 'EST-2511', description: 'Scale inhibitor for cooling tower with high-hardness makeup water', unitPrice: 155000, uom: 'kg', primaryUseCase: 'cooling tower scale inhibitor calcium silica high hardness', keyBenefits: JSON.stringify(['Controls calcium and silica scale', 'Effective at high cycles of concentration', 'Reduces water consumption']), typicalVolumeKg: 600 },
    { id: 'p-ct04', familyId: 'fam-cooling', name: 'GreenCool 200', sku: 'GC-200', description: 'Eco-friendly cooling water treatment with biodegradable chemistry', unitPrice: 195000, uom: 'liter', primaryUseCase: 'cooling water green eco-friendly biodegradable treatment', keyBenefits: JSON.stringify(['Zero phosphate formula', 'Meets PROPER environmental rating', 'Low toxicity discharge']), typicalVolumeKg: 350 },
    { id: 'p-ct05', familyId: 'fam-cooling', name: 'RadCool', sku: 'RC-001', description: 'Radiator coolant and corrosion inhibitor for heavy equipment', unitPrice: 85000, uom: 'liter', primaryUseCase: 'radiator coolant heavy equipment mining truck loader', keyBenefits: JSON.stringify(['Extended-life formula', 'Protects all metals in cooling system', 'Prevents cavitation erosion']), typicalVolumeKg: 2000 },
    { id: 'p-ct06', familyId: 'fam-cooling', name: 'EonCor CT 3300', sku: 'ECT-3300', description: 'Corrosion inhibitor for cooling tower recirculating water', unitPrice: 175000, uom: 'kg', primaryUseCase: 'cooling tower corrosion inhibitor recirculating water steel copper', keyBenefits: JSON.stringify(['Protects mild steel and copper', 'Molybdate-based program', 'Chromate-free formulation']), typicalVolumeKg: 450 },
    { id: 'p-ct07', familyId: 'fam-cooling', name: 'EonChill 4400', sku: 'ECH-4400', description: 'Closed-loop chiller treatment for corrosion and biological control', unitPrice: 220000, uom: 'kg', primaryUseCase: 'closed loop chiller corrosion biocide HVAC building', keyBenefits: JSON.stringify(['All-in-one treatment', 'Low maintenance dosing', 'Compatible with glycol systems']), typicalVolumeKg: 200 },

    // Lubricant (5)
    { id: 'p-lu01', familyId: 'fam-lube', name: 'EonWire 230', sku: 'EWR-230', description: 'Wire rope lubricant for cranes, hoists, and mooring equipment', unitPrice: 145000, uom: 'kg', primaryUseCase: 'wire rope lubricant crane hoist mooring port shipyard', keyBenefits: JSON.stringify(['Penetrates to core strands', 'Saltwater displacement', 'Extends wire rope life 40%']), typicalVolumeKg: 300 },
    { id: 'p-lu02', familyId: 'fam-lube', name: 'EonRom 100', sku: 'ER-100', description: 'Multi-purpose industrial grease for bearings and gears', unitPrice: 95000, uom: 'kg', primaryUseCase: 'industrial grease bearing gear multipurpose lubrication', keyBenefits: JSON.stringify(['High load capacity', 'Water resistant', 'Wide temperature range -20 to 180°C']), typicalVolumeKg: 500 },
    { id: 'p-lu03', familyId: 'fam-lube', name: 'EonRom 200', sku: 'ER-200', description: 'Heavy-duty open gear lubricant for mining and cement equipment', unitPrice: 210000, uom: 'kg', primaryUseCase: 'open gear lubricant mining cement kiln ball mill heavy duty', keyBenefits: JSON.stringify(['Extreme pressure performance', 'Adhesive — stays on gear teeth', 'Reduces wear and noise']), typicalVolumeKg: 800 },
    { id: 'p-lu04', familyId: 'fam-lube', name: 'EonChain 150', sku: 'ECN-150', description: 'Chain lubricant for conveyor systems in mining and manufacturing', unitPrice: 115000, uom: 'kg', primaryUseCase: 'chain lubricant conveyor mining manufacturing palm oil', keyBenefits: JSON.stringify(['Anti-fling formula', 'Resists coal dust contamination', 'High-temperature stable']), typicalVolumeKg: 600 },
    { id: 'p-lu05', familyId: 'fam-lube', name: 'EonSlip 380', sku: 'ESL-380', description: 'Anti-seize compound for bolts, flanges, and threaded connections', unitPrice: 285000, uom: 'kg', primaryUseCase: 'anti-seize bolt flange threaded connection high temperature', keyBenefits: JSON.stringify(['Prevents galling and seizing', 'Effective to 1100°C', 'Copper and graphite based']), typicalVolumeKg: 100 },

    // Oil Spill Dispersant (4)
    { id: 'p-os01', familyId: 'fam-oilspill', name: 'EonSpill 500', sku: 'ESP-500', description: 'Type 2 oil spill dispersant for marine and port use', unitPrice: 225000, uom: 'liter', primaryUseCase: 'oil spill dispersant marine port emergency response', keyBenefits: JSON.stringify(['PROPER certified', 'Effective on crude and fuel oil', 'Rapid dispersion in tropical waters']), typicalVolumeKg: 500 },
    { id: 'p-os02', familyId: 'fam-oilspill', name: 'QuickBreak 600', sku: 'QB-600', description: 'Fast-acting shoreline and beach cleaning dispersant', unitPrice: 185000, uom: 'liter', primaryUseCase: 'shoreline cleaning oil spill beach coastal remediation', keyBenefits: JSON.stringify(['Shoreline-safe formulation', 'Biodegradable surfactant', 'Can be applied by backpack sprayer']), typicalVolumeKg: 300 },
    { id: 'p-os03', familyId: 'fam-oilspill', name: 'EonSorb 100', sku: 'ESO-100', description: 'Oil-selective absorbent pads and booms for spill containment', unitPrice: 350000, uom: 'kg', primaryUseCase: 'oil absorbent pads booms spill containment port industrial', keyBenefits: JSON.stringify(['Hydrophobic — repels water', 'Absorbs 15x own weight', 'Reusable up to 3 times']), typicalVolumeKg: 200 },
    { id: 'p-os04', familyId: 'fam-oilspill', name: 'EonKit SP 900', sku: 'EKS-900', description: 'Complete spill response kit for ports and vessels', unitPrice: 475000, uom: 'kg', primaryUseCase: 'spill kit response vessel port IMO MARPOL compliance', keyBenefits: JSON.stringify(['IMO SOPEP compliant', 'Includes dispersant absorbent and PPE', 'Ready-to-deploy packaging']), typicalVolumeKg: 50 },

    // Fire Safety (4)
    { id: 'p-fi01', familyId: 'fam-fire', name: 'FireShield 105', sku: 'FS-105', description: 'AFFF 3% firefighting foam concentrate for hydrocarbon fires', unitPrice: 385000, uom: 'liter', primaryUseCase: 'firefighting foam AFFF hydrocarbon fire marine industrial', keyBenefits: JSON.stringify(['3% proportioning rate', 'IMO MSC approved', 'Effective on Class B fires']), typicalVolumeKg: 400 },
    { id: 'p-fi02', familyId: 'fam-fire', name: 'FireShield 108', sku: 'FS-108', description: 'AR-AFFF 3x3 foam for alcohol and polar solvent fires', unitPrice: 450000, uom: 'liter', primaryUseCase: 'AR-AFFF foam alcohol polar solvent fire petrochemical', keyBenefits: JSON.stringify(['Dual-purpose — hydrocarbon and polar', 'Forms polymer membrane', 'Extended shelf life 20 years']), typicalVolumeKg: 300 },
    { id: 'p-fi03', familyId: 'fam-fire', name: 'FireShield Eco 200', sku: 'FSE-200', description: 'Fluorine-free firefighting foam concentrate', unitPrice: 420000, uom: 'liter', primaryUseCase: 'fluorine-free foam F3 firefighting environmental PFAS-free', keyBenefits: JSON.stringify(['Zero PFAS content', 'Meets new environmental regulations', 'Performance equivalent to AFFF']), typicalVolumeKg: 250 },
    { id: 'p-fi04', familyId: 'fam-fire', name: 'FireShield Marine 300', sku: 'FSM-300', description: 'Marine-approved foam for engine room and helideck systems', unitPrice: 495000, uom: 'liter', primaryUseCase: 'marine foam engine room helideck ship offshore platform', keyBenefits: JSON.stringify(['SOLAS/IMO approved', 'Seawater compatible', 'Low viscosity for long piping runs']), typicalVolumeKg: 500 },

    // Fuel Additive (5)
    { id: 'p-fu01', familyId: 'fam-fuel', name: 'EonFuel Additive', sku: 'EFA-001', description: 'Multi-functional diesel fuel additive for performance and storage', unitPrice: 265000, uom: 'liter', primaryUseCase: 'diesel additive performance cetane booster fuel stabilizer', keyBenefits: JSON.stringify(['Improves cetane by 3-5 points', 'Prevents fuel degradation', 'Cleans injectors']), typicalVolumeKg: 400 },
    { id: 'p-fu02', familyId: 'fam-fuel', name: 'CoalGuard 810', sku: 'CG-810', description: 'Coal dust suppressant and spontaneous combustion inhibitor', unitPrice: 75000, uom: 'liter', primaryUseCase: 'coal dust suppression spontaneous combustion mining stockpile', keyBenefits: JSON.stringify(['Prevents spontaneous combustion', 'Dust suppression in stockpiles', 'Reduces coal loss from wind']), typicalVolumeKg: 5000 },
    { id: 'p-fu03', familyId: 'fam-fuel', name: 'CoalGuard 575', sku: 'CG-575', description: 'Conveyor belt anti-caking and coal flow improver', unitPrice: 85000, uom: 'liter', primaryUseCase: 'conveyor coal flow improver anti-caking mining belt', keyBenefits: JSON.stringify(['Prevents coal buildup on belts', 'Improves material flow', 'Reduces conveyor downtime']), typicalVolumeKg: 3000 },
    { id: 'p-fu04', familyId: 'fam-fuel', name: 'EonMar Fuel 400', sku: 'EMF-400', description: 'Marine fuel oil treatment for heavy fuel and MDO', unitPrice: 195000, uom: 'liter', primaryUseCase: 'marine fuel treatment HFO MDO sludge dispersant ship', keyBenefits: JSON.stringify(['Disperses sludge and asphaltenes', 'Improves combustion efficiency', 'Reduces stack emissions']), typicalVolumeKg: 600 },
    { id: 'p-fu05', familyId: 'fam-fuel', name: 'EonBio Diesel 250', sku: 'EBD-250', description: 'Biocide for diesel fuel storage tanks to prevent microbial growth', unitPrice: 310000, uom: 'liter', primaryUseCase: 'diesel tank biocide microbial contamination fuel bug', keyBenefits: JSON.stringify(['Kills diesel bug (HUM)', 'Prevents filter blockage', 'Effective in B20-B30 biodiesel blends']), typicalVolumeKg: 100 },

    // Additional products to reach 50 (8 more spread across families)
    { id: 'p-bo09', familyId: 'fam-boiler', name: 'EonSteam 7500', sku: 'EST-7500', description: 'Volatile oxygen scavenger for high-pressure boiler systems', unitPrice: 325000, uom: 'kg', primaryUseCase: 'high pressure boiler oxygen scavenger volatile carbohydrazide', keyBenefits: JSON.stringify(['Effective above 100 bar', 'FDA-approved for food industry boilers', 'No dissolved solids contribution']), typicalVolumeKg: 150 },
    { id: 'p-co08', familyId: 'fam-coating', name: 'EonDeck 890', sku: 'EDK-890', description: 'Non-skid deck coating for ships and offshore platforms', unitPrice: 235000, uom: 'kg', primaryUseCase: 'deck coating non-skid ship offshore platform marine safety', keyBenefits: JSON.stringify(['IMO MSC non-skid compliant', 'Excellent UV and abrasion resistance', 'Available in safety colors']), typicalVolumeKg: 400 },
    { id: 'p-ct08', familyId: 'fam-cooling', name: 'EonPoly CT 5500', sku: 'EPC-5500', description: 'Polymeric dispersant for high-silt cooling water in coastal plants', unitPrice: 145000, uom: 'kg', primaryUseCase: 'cooling tower dispersant silt fouling coastal plant tropical', keyBenefits: JSON.stringify(['Controls silt and mud fouling', 'Effective in high-turbidity water', 'Compatible with biocide programs']), typicalVolumeKg: 500 },
    { id: 'p-lu06', familyId: 'fam-lube', name: 'EonHydra 500', sku: 'EH-500', description: 'Hydraulic oil for marine deck equipment and cranes', unitPrice: 165000, uom: 'liter', primaryUseCase: 'hydraulic oil marine crane deck equipment winch', keyBenefits: JSON.stringify(['Zinc-free anti-wear', 'Excellent water separation', 'Suitable for tropical conditions']), typicalVolumeKg: 1000 },
    { id: 'p-cl08', familyId: 'fam-cleaning', name: 'EonAC 700', sku: 'EAC-700', description: 'Evaporator and condenser coil cleaner for HVAC and chillers', unitPrice: 115000, uom: 'liter', primaryUseCase: 'AC coil cleaner evaporator condenser HVAC chiller', keyBenefits: JSON.stringify(['Self-rinsing formula', 'Non-corrosive to aluminum fins', 'Restores cooling efficiency']), typicalVolumeKg: 400 },
    { id: 'p-os05', familyId: 'fam-oilspill', name: 'EonBoom 250', sku: 'EBM-250', description: 'Inflatable oil containment boom for port and harbor use', unitPrice: 500000, uom: 'kg', primaryUseCase: 'oil containment boom port harbor spill response marine', keyBenefits: JSON.stringify(['Rapid deployment', 'Self-inflating design', 'ASTM F2084 certified']), typicalVolumeKg: 100 },
    { id: 'p-fu06', familyId: 'fam-fuel', name: 'EonCetan 350', sku: 'ECT-350', description: 'Premium cetane improver for Indonesian B35 biodiesel blend', unitPrice: 245000, uom: 'liter', primaryUseCase: 'cetane improver B35 biodiesel Indonesian diesel performance', keyBenefits: JSON.stringify(['Optimized for B35 mandate', 'Reduces cold start smoke', 'Improves power output 5%']), typicalVolumeKg: 300 },
    { id: 'p-fi05', familyId: 'fam-fire', name: 'FireShield Dry 400', sku: 'FSD-400', description: 'ABC dry chemical powder for portable extinguisher refill', unitPrice: 65000, uom: 'kg', primaryUseCase: 'dry chemical powder extinguisher refill ABC fire safety', keyBenefits: JSON.stringify(['Monoammonium phosphate based', 'Effective on A B C fires', 'Free-flowing non-caking']), typicalVolumeKg: 500 },
  ];
  for (const r of products) await db.insert(schema.products).values(r).onConflictDoNothing();

  // ── Product-Industry Fit (scored by relevance) ──────────────────────────────
  const pif = [
    // Maritime fits
    { id: 'pif-co01-mar', productId: 'p-co01', industryId: 'ind-maritime', fitScore: 0.96, useCase: 'Ship hull and marine structure epoxy coating' },
    { id: 'pif-co05-mar', productId: 'p-co05', industryId: 'ind-maritime', fitScore: 0.95, useCase: 'Anti-fouling paint for hull bottom in tropical waters' },
    { id: 'pif-fi04-mar', productId: 'p-fi04', industryId: 'ind-maritime', fitScore: 0.95, useCase: 'Engine room and helideck firefighting foam systems' },
    { id: 'pif-os01-mar', productId: 'p-os01', industryId: 'ind-maritime', fitScore: 0.95, useCase: 'Port and vessel oil spill response' },
    { id: 'pif-cl01-mar', productId: 'p-cl01', industryId: 'ind-maritime', fitScore: 0.92, useCase: 'Engine room and deck degreasing' },
    { id: 'pif-cl05-mar', productId: 'p-cl05', industryId: 'ind-maritime', fitScore: 0.94, useCase: 'Cargo hold cleaning between loads' },
    { id: 'pif-lu01-mar', productId: 'p-lu01', industryId: 'ind-maritime', fitScore: 0.93, useCase: 'Crane and mooring wire rope lubrication in ports' },
    { id: 'pif-co03-mar', productId: 'p-co03', industryId: 'ind-maritime', fitScore: 0.90, useCase: 'Vertical hull section coating in drydock' },
    { id: 'pif-co04-mar', productId: 'p-co04', industryId: 'ind-maritime', fitScore: 0.91, useCase: 'New build steel priming in shipyards' },
    { id: 'pif-cl07-mar', productId: 'p-cl07', industryId: 'ind-maritime', fitScore: 0.93, useCase: 'Fuel oil tank cleaning during drydock' },
    { id: 'pif-fi01-mar', productId: 'p-fi01', industryId: 'ind-maritime', fitScore: 0.90, useCase: 'Port and terminal fire protection' },
    { id: 'pif-fu04-mar', productId: 'p-fu04', industryId: 'ind-maritime', fitScore: 0.92, useCase: 'Marine HFO/MDO fuel treatment on vessels' },
    { id: 'pif-os04-mar', productId: 'p-os04', industryId: 'ind-maritime', fitScore: 0.94, useCase: 'SOPEP-compliant spill kit for vessels' },
    { id: 'pif-co07-mar', productId: 'p-co07', industryId: 'ind-maritime', fitScore: 0.88, useCase: 'Marine piling and waterfront structure protection' },
    { id: 'pif-lu06-mar', productId: 'p-lu06', industryId: 'ind-maritime', fitScore: 0.91, useCase: 'Marine deck crane and winch hydraulic systems' },
    { id: 'pif-co08-mar', productId: 'p-co08', industryId: 'ind-maritime', fitScore: 0.93, useCase: 'Ship deck and offshore platform non-skid coating' },
    { id: 'pif-cl03-mar', productId: 'p-cl03', industryId: 'ind-maritime', fitScore: 0.85, useCase: 'Marine engine cleaning and maintenance' },
    { id: 'pif-os02-mar', productId: 'p-os02', industryId: 'ind-maritime', fitScore: 0.88, useCase: 'Shoreline cleanup after oil spill incidents' },
    // Mining fits
    { id: 'pif-fu02-min', productId: 'p-fu02', industryId: 'ind-mining', fitScore: 0.96, useCase: 'Coal stockpile dust suppression and spontaneous combustion prevention' },
    { id: 'pif-fu03-min', productId: 'p-fu03', industryId: 'ind-mining', fitScore: 0.95, useCase: 'Coal conveyor belt anti-caking treatment' },
    { id: 'pif-co06-min', productId: 'p-co06', industryId: 'ind-mining', fitScore: 0.93, useCase: 'Slurry pipeline internal lining protection' },
    { id: 'pif-lu03-min', productId: 'p-lu03', industryId: 'ind-mining', fitScore: 0.94, useCase: 'Ball mill and kiln open gear lubrication' },
    { id: 'pif-ct05-min', productId: 'p-ct05', industryId: 'ind-mining', fitScore: 0.92, useCase: 'Heavy equipment radiator coolant for mining trucks' },
    { id: 'pif-b01-min',  productId: 'p-b01',  industryId: 'ind-mining', fitScore: 0.85, useCase: 'Coal processing plant boiler scale control' },
    { id: 'pif-lu04-min', productId: 'p-lu04', industryId: 'ind-mining', fitScore: 0.91, useCase: 'Mining conveyor chain lubrication' },
    { id: 'pif-co02-min', productId: 'p-co02', industryId: 'ind-mining', fitScore: 0.82, useCase: 'Rust rehabilitation of mining equipment' },
    { id: 'pif-lu02-min', productId: 'p-lu02', industryId: 'ind-mining', fitScore: 0.85, useCase: 'Mining equipment bearing and gear lubrication' },
    { id: 'pif-cl01-min', productId: 'p-cl01', industryId: 'ind-mining', fitScore: 0.78, useCase: 'Mining equipment cleaning and degreasing' },
    { id: 'pif-fi01-min', productId: 'p-fi01', industryId: 'ind-mining', fitScore: 0.80, useCase: 'Mining site fire safety and fuel depot protection' },
    { id: 'pif-b03-min',  productId: 'p-b03',  industryId: 'ind-mining', fitScore: 0.83, useCase: 'Mine site boiler descaling during shutdown' },
    // General Industrial fits
    { id: 'pif-b01-gen',  productId: 'p-b01',  industryId: 'ind-general', fitScore: 0.92, useCase: 'Factory boiler scale control in palm oil and food processing' },
    { id: 'pif-b08-gen',  productId: 'p-b08',  industryId: 'ind-general', fitScore: 0.90, useCase: 'Palm oil mill fire tube boiler all-in-one treatment' },
    { id: 'pif-ct01-gen', productId: 'p-ct01', industryId: 'ind-general', fitScore: 0.88, useCase: 'Factory cooling tower biocide treatment' },
    { id: 'pif-ct03-gen', productId: 'p-ct03', industryId: 'ind-general', fitScore: 0.87, useCase: 'Cooling tower scale control in industrial plants' },
    { id: 'pif-ct06-gen', productId: 'p-ct06', industryId: 'ind-general', fitScore: 0.86, useCase: 'Cooling water corrosion inhibitor for steel and petrochemical' },
    { id: 'pif-cl06-gen', productId: 'p-cl06', industryId: 'ind-general', fitScore: 0.85, useCase: 'Stainless steel passivation in food & beverage plants' },
    { id: 'pif-b05-gen',  productId: 'p-b05',  industryId: 'ind-general', fitScore: 0.88, useCase: 'Boiler feedwater oxygen scavenging in process plants' },
    { id: 'pif-b06-gen',  productId: 'p-b06',  industryId: 'ind-general', fitScore: 0.85, useCase: 'Condensate line protection in cement and steel plants' },
    { id: 'pif-fi02-gen', productId: 'p-fi02', industryId: 'ind-general', fitScore: 0.82, useCase: 'Petrochemical plant fire protection' },
    { id: 'pif-lu02-gen', productId: 'p-lu02', industryId: 'ind-general', fitScore: 0.80, useCase: 'General factory bearing and gear lubrication' },
    { id: 'pif-cl04-gen', productId: 'p-cl04', industryId: 'ind-general', fitScore: 0.82, useCase: 'General factory and plant cleaning' },
    { id: 'pif-ct07-gen', productId: 'p-ct07', industryId: 'ind-general', fitScore: 0.84, useCase: 'HVAC chiller treatment in commercial buildings' },
    { id: 'pif-cl08-gen', productId: 'p-cl08', industryId: 'ind-general', fitScore: 0.83, useCase: 'HVAC coil cleaning in food processing and manufacturing' },
    { id: 'pif-b04-gen',  productId: 'p-b04',  industryId: 'ind-general', fitScore: 0.84, useCase: 'Heat exchanger descaling in manufacturing plants' },
  ];
  for (const r of pif) await db.insert(schema.productIndustryFit).values(r).onConflictDoNothing();

  // ── Users ───────────────────────────────────────────────────────────────────
  const users = [
    { id: 'u-01', name: 'Budi Santoso', email: 'budi.santoso@eonchemicals.com', role: 'manager' as const, territory: 'National' },
    { id: 'u-02', name: 'Andi Wibowo', email: 'andi.wibowo@eonchemicals.com', role: 'sales_rep' as const, territory: 'Jakarta / Jawa Barat' },
    { id: 'u-03', name: 'Dewi Lestari', email: 'dewi.lestari@eonchemicals.com', role: 'sales_rep' as const, territory: 'Surabaya / Jawa Timur' },
    { id: 'u-04', name: 'Rahmat Hidayat', email: 'rahmat.hidayat@eonchemicals.com', role: 'sales_rep' as const, territory: 'Kalimantan' },
    { id: 'u-05', name: 'Siti Nurhaliza', email: 'siti.nurhaliza@eonchemicals.com', role: 'sales_rep' as const, territory: 'Sulawesi / Indonesia Timur' },
  ];
  for (const r of users) await db.insert(schema.users).values(r).onConflictDoNothing();

  // ── Opportunity Stages ──────────────────────────────────────────────────────
  const stages = [
    { id: 'stg-1', name: 'Prospect',   code: 'PROSPECT',  order: 1, probability: 0.10, description: 'Initial contact or lead identified' },
    { id: 'stg-2', name: 'Qualify',    code: 'QUALIFY',   order: 2, probability: 0.25, description: 'Pain points and budget confirmed' },
    { id: 'stg-3', name: 'Propose',    code: 'PROPOSE',   order: 3, probability: 0.50, description: 'Formal proposal or quotation submitted' },
    { id: 'stg-4', name: 'Negotiate',  code: 'NEGOTIATE', order: 4, probability: 0.75, description: 'Commercial terms under discussion' },
    { id: 'stg-5', name: 'Close',      code: 'CLOSE',     order: 5, probability: 0.90, description: 'Final sign-off expected imminently' },
  ];
  for (const r of stages) await db.insert(schema.opportunityStages).values(r).onConflictDoNothing();

  // ── Accounts (25) ───────────────────────────────────────────────────────────
  const accounts = [
    // Maritime (10)
    { id: 'acc-01', name: 'PT Pelindo', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 28000000000000, employeeCount: 6500, tier: 'strategic' as const, status: 'active' as const, website: 'pelindo.co.id', tags: JSON.stringify(['port-operator', 'BUMN', 'strategic']) },
    { id: 'acc-02', name: 'PT Pertamina Trans Kontinental', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 5200000000000, employeeCount: 2800, tier: 'strategic' as const, status: 'active' as const, website: 'ptk.pertamina.com', tags: JSON.stringify(['marine-logistics', 'pertamina-group', 'tanker']) },
    { id: 'acc-03', name: 'PT Djakarta Lloyd', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 1800000000000, employeeCount: 950, tier: 'key' as const, status: 'active' as const, website: 'djakartalloyd.co.id', tags: JSON.stringify(['shipping', 'BUMN', 'container']) },
    { id: 'acc-04', name: 'PT ASDP Indonesia Ferry', industryId: 'ind-maritime', assignedUserId: 'u-03', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 4100000000000, employeeCount: 3200, tier: 'strategic' as const, status: 'active' as const, website: 'indonesiaferry.co.id', tags: JSON.stringify(['ferry', 'BUMN', 'ro-ro']) },
    { id: 'acc-05', name: 'PT Dok dan Perkapalan Surabaya', industryId: 'ind-maritime', assignedUserId: 'u-03', country: 'Indonesia', state: 'Jawa Timur', city: 'Surabaya', annualRevenue: 980000000000, employeeCount: 1400, tier: 'key' as const, status: 'active' as const, website: 'dps-surabaya.co.id', tags: JSON.stringify(['shipyard', 'drydock', 'repair']) },
    { id: 'acc-06', name: 'PT PAL Indonesia', industryId: 'ind-maritime', assignedUserId: 'u-03', country: 'Indonesia', state: 'Jawa Timur', city: 'Surabaya', annualRevenue: 3500000000000, employeeCount: 4100, tier: 'strategic' as const, status: 'active' as const, website: 'pal.co.id', tags: JSON.stringify(['shipbuilder', 'BUMN', 'naval', 'strategic']) },
    { id: 'acc-07', name: 'PT Pelayaran Tempuran Emas', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 2200000000000, employeeCount: 1600, tier: 'key' as const, status: 'active' as const, website: 'temasline.com', tags: JSON.stringify(['container-shipping', 'domestic', 'TMAS']) },
    { id: 'acc-08', name: 'PT Batam Shipyard', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'Kepulauan Riau', city: 'Batam', annualRevenue: 750000000000, employeeCount: 800, tier: 'standard' as const, status: 'active' as const, tags: JSON.stringify(['shipyard', 'repair', 'offshore']) },
    { id: 'acc-09', name: 'PT Soechi Lines', industryId: 'ind-maritime', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 3800000000000, employeeCount: 1200, tier: 'key' as const, status: 'active' as const, website: 'soechilines.co.id', tags: JSON.stringify(['tanker', 'chemical-tanker', 'HITS']) },
    { id: 'acc-10', name: 'Pelabuhan Makassar', industryId: 'ind-maritime', assignedUserId: 'u-05', country: 'Indonesia', state: 'Sulawesi Selatan', city: 'Makassar', annualRevenue: 620000000000, employeeCount: 450, tier: 'standard' as const, status: 'active' as const, tags: JSON.stringify(['port', 'eastern-indonesia', 'hub']) },
    // Mining (8)
    { id: 'acc-11', name: 'PT Adaro Energy', industryId: 'ind-mining', assignedUserId: 'u-04', country: 'Indonesia', state: 'Kalimantan Selatan', city: 'Balangan', annualRevenue: 65000000000000, employeeCount: 5500, tier: 'strategic' as const, status: 'active' as const, website: 'adaro.com', tags: JSON.stringify(['coal', 'kalimantan', 'major-miner', 'listed']) },
    { id: 'acc-12', name: 'PT Bukit Asam', industryId: 'ind-mining', assignedUserId: 'u-03', country: 'Indonesia', state: 'Sumatera Selatan', city: 'Tanjung Enim', annualRevenue: 35000000000000, employeeCount: 4200, tier: 'strategic' as const, status: 'active' as const, website: 'ptba.co.id', tags: JSON.stringify(['coal', 'BUMN', 'sumatera', 'listed']) },
    { id: 'acc-13', name: 'PT Freeport Indonesia', industryId: 'ind-mining', assignedUserId: 'u-05', country: 'Indonesia', state: 'Papua', city: 'Timika', annualRevenue: 120000000000000, employeeCount: 28000, tier: 'strategic' as const, status: 'active' as const, website: 'ptfi.co.id', tags: JSON.stringify(['copper', 'gold', 'papua', 'major-miner']) },
    { id: 'acc-14', name: 'PT Vale Indonesia', industryId: 'ind-mining', assignedUserId: 'u-05', country: 'Indonesia', state: 'Sulawesi Selatan', city: 'Sorowako', annualRevenue: 18000000000000, employeeCount: 3800, tier: 'strategic' as const, status: 'active' as const, website: 'vale.com/indonesia', tags: JSON.stringify(['nickel', 'sulawesi', 'smelter']) },
    { id: 'acc-15', name: 'PT Kaltim Prima Coal', industryId: 'ind-mining', assignedUserId: 'u-04', country: 'Indonesia', state: 'Kalimantan Timur', city: 'Sangatta', annualRevenue: 42000000000000, employeeCount: 5000, tier: 'strategic' as const, status: 'active' as const, website: 'kpc.co.id', tags: JSON.stringify(['coal', 'kalimantan', 'export', 'major-miner']) },
    { id: 'acc-16', name: 'PT Bayan Resources', industryId: 'ind-mining', assignedUserId: 'u-04', country: 'Indonesia', state: 'Kalimantan Timur', city: 'Samarinda', annualRevenue: 28000000000000, employeeCount: 3200, tier: 'key' as const, status: 'active' as const, website: 'bfrg.net', tags: JSON.stringify(['coal', 'kalimantan', 'listed']) },
    { id: 'acc-17', name: 'PT Aneka Tambang (Antam)', industryId: 'ind-mining', assignedUserId: 'u-05', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 40000000000000, employeeCount: 3500, tier: 'strategic' as const, status: 'active' as const, website: 'antam.com', tags: JSON.stringify(['nickel', 'gold', 'BUMN', 'multi-commodity']) },
    { id: 'acc-18', name: 'PT Berau Coal', industryId: 'ind-mining', assignedUserId: 'u-04', country: 'Indonesia', state: 'Kalimantan Timur', city: 'Tanjung Redeb', annualRevenue: 15000000000000, employeeCount: 2800, tier: 'key' as const, status: 'active' as const, website: 'beraucoal.co.id', tags: JSON.stringify(['coal', 'kalimantan', 'export']) },
    // General Industrial (7)
    { id: 'acc-19', name: 'PT Krakatau Steel', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'Banten', city: 'Cilegon', annualRevenue: 22000000000000, employeeCount: 6200, tier: 'strategic' as const, status: 'active' as const, website: 'kfrg.co.id', tags: JSON.stringify(['steel', 'BUMN', 'heavy-industry']) },
    { id: 'acc-20', name: 'PT Indofood', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 95000000000000, employeeCount: 98000, tier: 'strategic' as const, status: 'active' as const, website: 'indofood.com', tags: JSON.stringify(['food-beverage', 'manufacturing', 'salim-group']) },
    { id: 'acc-21', name: 'PT Wilmar International', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 85000000000000, employeeCount: 12000, tier: 'strategic' as const, status: 'active' as const, website: 'wilmar-international.com', tags: JSON.stringify(['palm-oil', 'refinery', 'oleochemical']) },
    { id: 'acc-22', name: 'PT Chandra Asri Petrochemical', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'Banten', city: 'Cilegon', annualRevenue: 48000000000000, employeeCount: 2800, tier: 'strategic' as const, status: 'active' as const, website: 'chandraasri.com', tags: JSON.stringify(['petrochemical', 'ethylene', 'polyethylene']) },
    { id: 'acc-23', name: 'PT Semen Indonesia', industryId: 'ind-general', assignedUserId: 'u-03', country: 'Indonesia', state: 'Jawa Timur', city: 'Gresik', annualRevenue: 35000000000000, employeeCount: 7500, tier: 'strategic' as const, status: 'active' as const, website: 'sig.id', tags: JSON.stringify(['cement', 'BUMN', 'heavy-industry']) },
    { id: 'acc-24', name: 'PT Unilever Indonesia', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 42000000000000, employeeCount: 5000, tier: 'key' as const, status: 'active' as const, website: 'unilever.co.id', tags: JSON.stringify(['FMCG', 'manufacturing', 'food-beverage']) },
    { id: 'acc-25', name: 'PT Astra International', industryId: 'ind-general', assignedUserId: 'u-02', country: 'Indonesia', state: 'DKI Jakarta', city: 'Jakarta', annualRevenue: 280000000000000, employeeCount: 180000, tier: 'strategic' as const, status: 'active' as const, website: 'astra.co.id', tags: JSON.stringify(['automotive', 'heavy-equipment', 'mining-contractor', 'conglomerate']) },
  ];
  for (const r of accounts) await db.insert(schema.accounts).values(r).onConflictDoNothing();

  // ── Account Purchase History (30 records) ──────────────────────────────────
  const history = [
    // PT Pelindo — heavy maritime buyer
    { id: 'h-01', accountId: 'acc-01', productId: 'p-co01', volumeKg: 800, totalValue: 228000000, purchaseDate: '2025-03-10', isRecurring: true, notes: 'Annual port structure coating supply' },
    { id: 'h-02', accountId: 'acc-01', productId: 'p-os01', volumeKg: 500, totalValue: 112500000, purchaseDate: '2025-04-15', isRecurring: true, notes: 'Oil spill dispersant stock replenishment' },
    { id: 'h-03', accountId: 'acc-01', productId: 'p-lu01', volumeKg: 300, totalValue: 43500000, purchaseDate: '2025-02-20', isRecurring: true, notes: 'Wire rope lubricant for port cranes' },
    { id: 'h-04', accountId: 'acc-01', productId: 'p-cl01', volumeKg: 2000, totalValue: 136000000, purchaseDate: '2025-05-01', isRecurring: true, notes: 'Port equipment cleaning supplies' },
    // PT Pertamina Trans Kontinental
    { id: 'h-05', accountId: 'acc-02', productId: 'p-fu04', volumeKg: 600, totalValue: 117000000, purchaseDate: '2025-01-15', isRecurring: true, notes: 'Marine fuel treatment for tanker fleet' },
    { id: 'h-06', accountId: 'acc-02', productId: 'p-fi01', volumeKg: 400, totalValue: 154000000, purchaseDate: '2025-03-20', isRecurring: true, notes: 'AFFF foam for vessel fire systems' },
    { id: 'h-07', accountId: 'acc-02', productId: 'p-co05', volumeKg: 800, totalValue: 304000000, purchaseDate: '2024-11-05', isRecurring: false, notes: 'Anti-fouling paint for 3 tankers during drydock' },
    // PT PAL Indonesia — shipyard
    { id: 'h-08', accountId: 'acc-06', productId: 'p-co04', volumeKg: 600, totalValue: 159000000, purchaseDate: '2025-02-10', isRecurring: true, notes: 'Zinc-rich primer for new build program' },
    { id: 'h-09', accountId: 'acc-06', productId: 'p-co01', volumeKg: 1000, totalValue: 285000000, purchaseDate: '2025-04-20', isRecurring: true, notes: 'Anti-rust epoxy for hull coating' },
    { id: 'h-10', accountId: 'acc-06', productId: 'p-cl07', volumeKg: 800, totalValue: 78400000, purchaseDate: '2025-01-25', isRecurring: true, notes: 'Tank cleaning chemicals for repair jobs' },
    // PT Adaro Energy — coal mining
    { id: 'h-11', accountId: 'acc-11', productId: 'p-fu02', volumeKg: 5000, totalValue: 375000000, purchaseDate: '2025-03-01', isRecurring: true, notes: 'CoalGuard for stockpile management' },
    { id: 'h-12', accountId: 'acc-11', productId: 'p-fu03', volumeKg: 3000, totalValue: 255000000, purchaseDate: '2025-02-15', isRecurring: true, notes: 'Conveyor belt treatment' },
    { id: 'h-13', accountId: 'acc-11', productId: 'p-ct05', volumeKg: 2000, totalValue: 170000000, purchaseDate: '2025-04-10', isRecurring: true, notes: 'Radiator coolant for CAT 793 fleet' },
    { id: 'h-14', accountId: 'acc-11', productId: 'p-lu03', volumeKg: 800, totalValue: 168000000, purchaseDate: '2025-01-20', isRecurring: true, notes: 'Open gear lube for crusher and conveyor drives' },
    // PT Kaltim Prima Coal
    { id: 'h-15', accountId: 'acc-15', productId: 'p-fu02', volumeKg: 4000, totalValue: 300000000, purchaseDate: '2025-02-28', isRecurring: true, notes: 'Coal stockpile dust suppressant' },
    { id: 'h-16', accountId: 'acc-15', productId: 'p-lu04', volumeKg: 600, totalValue: 69000000, purchaseDate: '2025-03-15', isRecurring: true, notes: 'Conveyor chain lubrication program' },
    // PT Freeport Indonesia
    { id: 'h-17', accountId: 'acc-13', productId: 'p-co06', volumeKg: 1000, totalValue: 245000000, purchaseDate: '2025-01-10', isRecurring: true, notes: 'Slurry pipeline coating for concentrate transport' },
    { id: 'h-18', accountId: 'acc-13', productId: 'p-b01', volumeKg: 500, totalValue: 92500000, purchaseDate: '2025-04-05', isRecurring: true, notes: 'Boiler scale inhibitor for concentrator plant' },
    // PT Krakatau Steel
    { id: 'h-19', accountId: 'acc-19', productId: 'p-b01', volumeKg: 700, totalValue: 129500000, purchaseDate: '2025-02-01', isRecurring: true, notes: 'Boiler scale treatment for steel mill' },
    { id: 'h-20', accountId: 'acc-19', productId: 'p-ct01', volumeKg: 400, totalValue: 66000000, purchaseDate: '2025-03-10', isRecurring: true, notes: 'Cooling tower biocide program' },
    { id: 'h-21', accountId: 'acc-19', productId: 'p-ct03', volumeKg: 600, totalValue: 93000000, purchaseDate: '2025-01-15', isRecurring: true, notes: 'Cooling tower scale inhibitor' },
    { id: 'h-22', accountId: 'acc-19', productId: 'p-b03', volumeKg: 800, totalValue: 76000000, purchaseDate: '2024-12-20', isRecurring: false, notes: 'Annual boiler descaling during shutdown' },
    // PT Wilmar (palm oil)
    { id: 'h-23', accountId: 'acc-21', productId: 'p-b08', volumeKg: 700, totalValue: 115500000, purchaseDate: '2025-03-05', isRecurring: true, notes: 'Boiler treatment for palm oil mill' },
    { id: 'h-24', accountId: 'acc-21', productId: 'p-ct02', volumeKg: 500, totalValue: 67500000, purchaseDate: '2025-02-10', isRecurring: true, notes: 'Algaecide for cooling tower — tropical algae issue' },
    // PT Semen Indonesia
    { id: 'h-25', accountId: 'acc-23', productId: 'p-lu03', volumeKg: 800, totalValue: 168000000, purchaseDate: '2025-01-08', isRecurring: true, notes: 'Open gear lube for kiln drives and ball mills' },
    { id: 'h-26', accountId: 'acc-23', productId: 'p-b05', volumeKg: 300, totalValue: 43500000, purchaseDate: '2025-04-01', isRecurring: true, notes: 'Oxygen scavenger for power plant boiler' },
    // PT Soechi Lines — tanker
    { id: 'h-27', accountId: 'acc-09', productId: 'p-cl07', volumeKg: 800, totalValue: 78400000, purchaseDate: '2025-02-25', isRecurring: true, notes: 'Fuel oil tank cleaning for fleet' },
    { id: 'h-28', accountId: 'acc-09', productId: 'p-co05', volumeKg: 1200, totalValue: 456000000, purchaseDate: '2024-10-15', isRecurring: false, notes: 'Anti-fouling paint during Singapore drydock' },
    // PT Indofood
    { id: 'h-29', accountId: 'acc-20', productId: 'p-b01', volumeKg: 500, totalValue: 92500000, purchaseDate: '2025-03-18', isRecurring: true, notes: 'Boiler scale treatment for noodle factory' },
    { id: 'h-30', accountId: 'acc-20', productId: 'p-cl06', volumeKg: 300, totalValue: 40500000, purchaseDate: '2025-01-22', isRecurring: true, notes: 'Stainless steel passivation for production lines' },
  ];
  for (const r of history) await db.insert(schema.accountProductHistory).values(r).onConflictDoNothing();

  // ── Opportunities (60) ──────────────────────────────────────────────────────
  const opps = [
    // Maritime — Active healthy (25 maritime opportunities total)
    { id: 'opp-01', accountId: 'acc-01', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-co01', name: 'Tanjung Priok Wharf Recoating Project', value: 2800000000, currency: 'IDR', closeDate: '2026-05-30', problemStatement: 'Severe tropical corrosion on Berth 1-3 steel structures at Tanjung Priok. Salt spray and high humidity accelerating coating failure. Need IMO-grade epoxy system.', useCase: 'wharf steel structure anti-rust coating marine tropical', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-02', accountId: 'acc-01', assignedUserId: 'u-02', stageId: 'stg-4', primaryProductId: 'p-os01', name: 'Pelindo Oil Spill Response Kit Rollout', value: 1500000000, currency: 'IDR', closeDate: '2026-04-15', problemStatement: 'Ministry of Transportation mandate for enhanced oil spill readiness at all major ports. Pelindo needs dispersant stockpile and response kits across 4 regional ports.', useCase: 'oil spill dispersant response kit port compliance', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-03', accountId: 'acc-02', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-fu04', name: 'Pertamina Fleet Marine Fuel Treatment Program', value: 3200000000, currency: 'IDR', closeDate: '2026-07-20', problemStatement: 'Fleet of 45 tankers experiencing injector fouling and sludge issues with low-sulfur fuel. Need comprehensive fuel treatment program.', useCase: 'marine fuel treatment HFO tanker fleet sludge dispersant', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-04', accountId: 'acc-02', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-fi04', name: 'Tanker Fleet Fire Safety Foam Replacement', value: 1850000000, currency: 'IDR', closeDate: '2026-06-15', problemStatement: 'Existing AFFF foam stocks expiring. Need marine-approved replacement for engine room and cargo deck systems on 30+ vessels.', useCase: 'marine firefighting foam AFFF tanker engine room SOLAS', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-05', accountId: 'acc-03', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-cl05', name: 'Djakarta Lloyd Cargo Hold Cleaning Contract', value: 680000000, currency: 'IDR', closeDate: '2026-06-30', problemStatement: 'Coal-to-grain cargo switches requiring thorough hold cleaning. Current chemicals not meeting P&I surveyor standards.', useCase: 'cargo hold cleaning coal grain switch P&I compliance', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-06', accountId: 'acc-04', assignedUserId: 'u-03', stageId: 'stg-3', primaryProductId: 'p-co01', name: 'ASDP Ferry Hull Coating Program', value: 4200000000, currency: 'IDR', closeDate: '2026-08-15', problemStatement: 'Fleet of 35 ro-ro ferries needs hull coating during biannual drydock schedule. Tropical biofouling reducing fuel efficiency by 15%.', useCase: 'ferry hull coating anti-rust biofouling tropical', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-07', accountId: 'acc-05', assignedUserId: 'u-03', stageId: 'stg-4', primaryProductId: 'p-co04', name: 'DPS New Build Zinc Primer Supply', value: 1200000000, currency: 'IDR', closeDate: '2026-05-15', problemStatement: 'Three new naval patrol boats under construction. Need weldable zinc-rich primer for all steel fabrication.', useCase: 'zinc primer shipyard new build naval steel fabrication', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-08', accountId: 'acc-06', assignedUserId: 'u-03', stageId: 'stg-3', primaryProductId: 'p-co05', name: 'PAL Indonesia Anti-Fouling Paint Contract', value: 5000000000, currency: 'IDR', closeDate: '2026-07-31', problemStatement: 'Annual anti-fouling paint supply for new builds and repair division. Current supplier Chugoku Paints increasing prices 20%.', useCase: 'anti-fouling paint shipbuilder supply contract self-polishing', competitorNotes: 'Incumbent: Chugoku Marine Paints. Price increase giving us opening.', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-09', accountId: 'acc-07', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-cl01', name: 'Tempuran Emas Fleet Cleaning Chemical Supply', value: 920000000, currency: 'IDR', closeDate: '2026-06-20', problemStatement: 'Standardizing cleaning chemical supply across 60-vessel container fleet. Need engine room degreaser and general wash.', useCase: 'fleet cleaning degreaser marine container vessel standardization', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-10', accountId: 'acc-08', assignedUserId: 'u-02', stageId: 'stg-1', primaryProductId: 'p-co01', name: 'Batam Shipyard Coating Package', value: 850000000, currency: 'IDR', closeDate: '2026-09-30', problemStatement: 'New repair contracts from Singapore-flagged vessels. Need IMO-approved coating system for competitive pricing.', useCase: 'shipyard coating repair offshore vessel Singapore', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-11', accountId: 'acc-09', assignedUserId: 'u-02', stageId: 'stg-4', primaryProductId: 'p-cl07', name: 'Soechi Lines Tank Cleaning Annual Contract', value: 1450000000, currency: 'IDR', closeDate: '2026-04-30', problemStatement: 'Chemical tanker fleet requires specialty tank cleaning chemicals for grade changes. Current product not meeting gas-free time requirements.', useCase: 'tank cleaning chemical tanker fuel oil crude gas-free', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-12', accountId: 'acc-10', assignedUserId: 'u-05', stageId: 'stg-2', primaryProductId: 'p-os01', name: 'Makassar Port Oil Spill Preparedness', value: 450000000, currency: 'IDR', closeDate: '2026-07-15', problemStatement: 'Recent minor spill incident exposed lack of response capability. Port authority requiring TIER 1 spill response equipment and chemicals.', useCase: 'oil spill preparedness port response dispersant absorbent', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    // Maritime — STALLED
    { id: 'opp-13', accountId: 'acc-03', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-co05', name: 'Djakarta Lloyd Hull Anti-Fouling Program', value: 1200000000, currency: 'IDR', closeDate: '2026-05-20', problemStatement: 'Fleet biofouling increasing fuel consumption. Anti-fouling paint proposal submitted but drydock scheduling uncertain due to monsoon season delays.', useCase: 'anti-fouling hull coating biofouling monsoon drydock scheduling', isStalled: true, stalledDays: 28, riskLevel: 'high' as const },
    { id: 'opp-14', accountId: 'acc-04', assignedUserId: 'u-03', stageId: 'stg-2', primaryProductId: 'p-fi01', name: 'ASDP Fire Safety System Upgrade', value: 2100000000, currency: 'IDR', closeDate: '2026-06-30', problemStatement: 'Safety audit identified aging foam systems on 15 ferries. Budget approval pending from BUMN ministry oversight.', useCase: 'ferry fire safety foam SOLAS compliance BUMN budget', isStalled: true, stalledDays: 35, riskLevel: 'high' as const },
    { id: 'opp-15', accountId: 'acc-08', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-co03', name: 'Batam Offshore Rig Coating Package', value: 680000000, currency: 'IDR', closeDate: '2026-07-01', problemStatement: 'Offshore rig repair contract won but customer procurement team unresponsive since initial meeting.', useCase: 'offshore rig coating epoxy vertical overhead repair', isStalled: true, stalledDays: 22, riskLevel: 'high' as const },
    { id: 'opp-16', accountId: 'acc-09', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-os04', name: 'Soechi Lines SOPEP Spill Kit Upgrade', value: 380000000, currency: 'IDR', closeDate: '2026-05-31', problemStatement: 'Port state control in Singapore flagged expired spill kit chemicals. Need replacement but procurement is slow.', useCase: 'SOPEP spill kit IMO compliance tanker port state control', isStalled: true, stalledDays: 18, riskLevel: 'medium' as const },
    // Additional maritime active
    { id: 'opp-17', accountId: 'acc-01', assignedUserId: 'u-02', stageId: 'stg-1', primaryProductId: 'p-lu01', name: 'Pelindo Crane Wire Rope Lubrication Program', value: 520000000, currency: 'IDR', closeDate: '2026-09-15', problemStatement: 'Wire rope failures on STS cranes at Tanjung Priok. New lubrication program needed to extend wire rope life in tropical salt environment.', useCase: 'wire rope lubricant crane port STS tropical salt', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-18', accountId: 'acc-06', assignedUserId: 'u-03', stageId: 'stg-5', primaryProductId: 'p-co04', name: 'PAL Naval Vessel Primer — Batch 2', value: 980000000, currency: 'IDR', closeDate: '2026-04-20', problemStatement: 'Second batch order for zinc primer on ongoing naval shipbuilding program. First batch performance excellent.', useCase: 'zinc primer naval vessel shipbuilding PAL Indonesia', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-19', accountId: 'acc-05', assignedUserId: 'u-03', stageId: 'stg-2', primaryProductId: 'p-co08', name: 'DPS Surabaya Deck Coating for Ferry Fleet', value: 750000000, currency: 'IDR', closeDate: '2026-08-30', problemStatement: 'Ferry operator requesting non-skid deck coating during scheduled drydock. Current coating worn smooth — safety hazard.', useCase: 'non-skid deck coating ferry drydock safety marine', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-20', accountId: 'acc-07', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-fu04', name: 'Tempuran Emas Marine Fuel Treatment', value: 1100000000, currency: 'IDR', closeDate: '2026-06-01', problemStatement: 'Container vessels switching to VLSFO experiencing injector deposits. Need fuel treatment to maintain engine performance.', useCase: 'marine fuel treatment VLSFO injector deposits container vessel', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-21', accountId: 'acc-10', assignedUserId: 'u-05', stageId: 'stg-1', primaryProductId: 'p-fi01', name: 'Makassar Port Fire Safety Depot', value: 350000000, currency: 'IDR', closeDate: '2026-10-01', problemStatement: 'Port fire department establishing chemical fire response depot. Need AFFF foam and dry chemical supply.', useCase: 'port fire safety AFFF foam depot Makassar', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-22', accountId: 'acc-02', assignedUserId: 'u-02', stageId: 'stg-5', primaryProductId: 'p-co05', name: 'Pertamina Tanker Anti-Fouling — Drydock Q2', value: 2400000000, currency: 'IDR', closeDate: '2026-04-25', problemStatement: '6 tankers scheduled for Singapore drydock Q2. Anti-fouling paint order for hull bottom coating. Specs already approved.', useCase: 'anti-fouling tanker drydock hull bottom paint', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-23', accountId: 'acc-06', assignedUserId: 'u-03', stageId: 'stg-2', primaryProductId: 'p-cl07', name: 'PAL Shipyard Tank Cleaning Chemical Supply', value: 560000000, currency: 'IDR', closeDate: '2026-08-01', problemStatement: 'Increasing ship repair orders require reliable tank cleaning chemical supply. Current local supplier inconsistent quality.', useCase: 'shipyard tank cleaning chemical supply quality consistency', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-24', accountId: 'acc-01', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-co07', name: 'Pelindo Marine Piling Protection', value: 1650000000, currency: 'IDR', closeDate: '2026-06-30', problemStatement: 'Concrete and steel piling at Tanjung Priok showing severe tropical marine corrosion. Coal tar epoxy protection needed for 200+ pilings.', useCase: 'marine piling protection coal tar epoxy port waterfront', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-25', accountId: 'acc-09', assignedUserId: 'u-02', stageId: 'stg-1', primaryProductId: 'p-lu06', name: 'Soechi Lines Deck Equipment Hydraulic Oil', value: 420000000, currency: 'IDR', closeDate: '2026-09-15', problemStatement: 'Fleet hydraulic oil standardization project. Current mix of brands causing maintenance complexity.', useCase: 'hydraulic oil marine deck equipment tanker standardization', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },

    // Mining — Active (20 mining opportunities total)
    { id: 'opp-26', accountId: 'acc-11', assignedUserId: 'u-04', stageId: 'stg-4', primaryProductId: 'p-fu02', name: 'Adaro Stockpile Dust Suppression Expansion', value: 2800000000, currency: 'IDR', closeDate: '2026-05-15', problemStatement: 'Expanding coal production to 60MT/year. Additional stockpile areas need CoalGuard 810 for spontaneous combustion prevention in tropical heat.', useCase: 'coal stockpile dust suppression spontaneous combustion Kalimantan', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-27', accountId: 'acc-11', assignedUserId: 'u-04', stageId: 'stg-3', primaryProductId: 'p-ct05', name: 'Adaro Heavy Equipment Coolant Program', value: 1850000000, currency: 'IDR', closeDate: '2026-06-30', problemStatement: 'Fleet of 200+ haul trucks and excavators requiring standardized radiator coolant. Current product causing cavitation erosion in Komatsu 930E engines.', useCase: 'radiator coolant mining truck heavy equipment fleet Kalimantan', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-28', accountId: 'acc-12', assignedUserId: 'u-03', stageId: 'stg-2', primaryProductId: 'p-b01', name: 'Bukit Asam Coal Processing Boiler Treatment', value: 980000000, currency: 'IDR', closeDate: '2026-07-15', problemStatement: 'Coal drying facility boilers experiencing scale buildup from high-silica feedwater. Current treatment ineffective.', useCase: 'boiler scale silica coal processing drying facility', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-29', accountId: 'acc-13', assignedUserId: 'u-05', stageId: 'stg-3', primaryProductId: 'p-co06', name: 'Freeport Slurry Pipeline Coating Renewal', value: 4500000000, currency: 'IDR', closeDate: '2026-06-20', problemStatement: '170km concentrate slurry pipeline from Grasberg to coast. Internal coating renewal due. Extreme abrasion conditions in highland Papua.', useCase: 'slurry pipeline internal coating mining concentrate transport abrasion', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-30', accountId: 'acc-13', assignedUserId: 'u-05', stageId: 'stg-2', primaryProductId: 'p-b05', name: 'Freeport Concentrator Boiler Program', value: 1200000000, currency: 'IDR', closeDate: '2026-08-31', problemStatement: 'New underground block cave mine needs boiler water treatment for concentrator plant. High altitude conditions affecting chemistry.', useCase: 'boiler oxygen scavenger concentrator high altitude mining', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-31', accountId: 'acc-14', assignedUserId: 'u-05', stageId: 'stg-3', primaryProductId: 'p-b01', name: 'Vale Nickel Smelter Boiler Chemical Supply', value: 1650000000, currency: 'IDR', closeDate: '2026-05-30', problemStatement: 'Nickel smelter boilers running at 80% due to scale and corrosion issues. Current Nalco program underperforming.', competitorNotes: 'Incumbent: Nalco/Ecolab. Performance issues giving us entry.', useCase: 'boiler treatment nickel smelter scale corrosion', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-32', accountId: 'acc-15', assignedUserId: 'u-04', stageId: 'stg-4', primaryProductId: 'p-fu02', name: 'KPC Coal Stockpile Management Program', value: 3500000000, currency: 'IDR', closeDate: '2026-05-10', problemStatement: 'Record coal production creating larger stockpiles. Spontaneous combustion incidents increasing during dry season. Insurance company requiring treatment.', useCase: 'coal stockpile spontaneous combustion prevention insurance requirement', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-33', accountId: 'acc-15', assignedUserId: 'u-04', stageId: 'stg-2', primaryProductId: 'p-lu03', name: 'KPC Crusher and Conveyor Lubrication', value: 1100000000, currency: 'IDR', closeDate: '2026-07-31', problemStatement: 'Open gear drives on crushers and conveyors wearing prematurely. Coal dust contamination reducing lubricant effectiveness.', useCase: 'open gear lubricant crusher conveyor coal dust mining', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-34', accountId: 'acc-16', assignedUserId: 'u-04', stageId: 'stg-3', primaryProductId: 'p-fu03', name: 'Bayan Resources Conveyor Treatment Program', value: 780000000, currency: 'IDR', closeDate: '2026-06-15', problemStatement: 'Coal sticking to conveyor belts causing spillage and downtime. Need anti-caking and flow improvement chemical for tropical wet conditions.', useCase: 'conveyor coal anti-caking flow improver tropical wet conditions', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-35', accountId: 'acc-17', assignedUserId: 'u-05', stageId: 'stg-2', primaryProductId: 'p-b01', name: 'Antam Nickel Smelter Boiler Upgrade', value: 2200000000, currency: 'IDR', closeDate: '2026-08-15', problemStatement: 'New RKEF nickel smelter commissioning in Halmahera. Complete boiler chemical program needed for 3 units.', useCase: 'nickel smelter RKEF boiler chemical program new plant commissioning', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-36', accountId: 'acc-18', assignedUserId: 'u-04', stageId: 'stg-1', primaryProductId: 'p-fu02', name: 'Berau Coal Stockpile Safety Program', value: 650000000, currency: 'IDR', closeDate: '2026-09-30', problemStatement: 'ESDM regulation compliance for coal stockpile management. Need dust suppression and combustion prevention.', useCase: 'coal stockpile ESDM regulation compliance dust suppression', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    // Mining — STALLED
    { id: 'opp-37', accountId: 'acc-12', assignedUserId: 'u-03', stageId: 'stg-3', primaryProductId: 'p-fu02', name: 'Bukit Asam Dust Suppression Trial', value: 550000000, currency: 'IDR', closeDate: '2026-05-31', problemStatement: 'Trial proposal submitted but site team reorganization has halted all new vendor approvals. Waiting for new procurement head.', useCase: 'coal dust suppression trial vendor approval procurement', isStalled: true, stalledDays: 30, riskLevel: 'high' as const },
    { id: 'opp-38', accountId: 'acc-16', assignedUserId: 'u-04', stageId: 'stg-2', primaryProductId: 'p-ct05', name: 'Bayan Resources Fleet Coolant Conversion', value: 420000000, currency: 'IDR', closeDate: '2026-07-15', problemStatement: 'Equipment division interested in switching from OEM coolant to EonChemicals. But maintenance manager prefers status quo.', useCase: 'radiator coolant fleet conversion mining equipment OEM', isStalled: true, stalledDays: 25, riskLevel: 'high' as const },
    { id: 'opp-39', accountId: 'acc-14', assignedUserId: 'u-05', stageId: 'stg-3', primaryProductId: 'p-co06', name: 'Vale Pipeline Relining Project', value: 1800000000, currency: 'IDR', closeDate: '2026-06-01', problemStatement: 'Slurry pipeline coating proposal submitted. CAPEX budget frozen pending nickel price recovery. Project on hold.', useCase: 'pipeline coating nickel slurry CAPEX freeze budget', isStalled: true, stalledDays: 40, riskLevel: 'high' as const },
    { id: 'opp-40', accountId: 'acc-18', assignedUserId: 'u-04', stageId: 'stg-2', primaryProductId: 'p-lu04', name: 'Berau Coal Conveyor Chain Lube Trial', value: 180000000, currency: 'IDR', closeDate: '2026-08-01', problemStatement: 'Sample sent 6 weeks ago but maintenance team has not conducted trial. Rainy season delaying all non-critical work.', useCase: 'conveyor chain lubricant trial rainy season delay', isStalled: true, stalledDays: 20, riskLevel: 'medium' as const },
    // Additional mining active
    { id: 'opp-41', accountId: 'acc-11', assignedUserId: 'u-04', stageId: 'stg-5', primaryProductId: 'p-lu03', name: 'Adaro Crusher Open Gear Lube — Annual PO', value: 1250000000, currency: 'IDR', closeDate: '2026-04-12', problemStatement: 'Annual purchase order renewal for open gear lubricant. Performance data excellent — 30% wear reduction documented.', useCase: 'open gear lubricant annual renewal crusher performance', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-42', accountId: 'acc-13', assignedUserId: 'u-05', stageId: 'stg-1', primaryProductId: 'p-fi01', name: 'Freeport Fire Safety Chemical Supply', value: 850000000, currency: 'IDR', closeDate: '2026-10-15', problemStatement: 'Grasberg underground mine fire safety upgrade. AFFF foam and dry chemical for 50+ fire stations underground.', useCase: 'underground mine fire safety AFFF foam dry chemical', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-43', accountId: 'acc-15', assignedUserId: 'u-04', stageId: 'stg-5', primaryProductId: 'p-fu03', name: 'KPC Conveyor Anti-Caking — Renewal', value: 920000000, currency: 'IDR', closeDate: '2026-04-18', problemStatement: 'Renewal of successful conveyor treatment program. Proven reduction in belt spillage by 60%.', useCase: 'conveyor anti-caking renewal coal belt spillage reduction', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-44', accountId: 'acc-17', assignedUserId: 'u-05', stageId: 'stg-1', primaryProductId: 'p-lu02', name: 'Antam Gold Processing Equipment Lubrication', value: 380000000, currency: 'IDR', closeDate: '2026-09-01', problemStatement: 'Pongkor gold mine ball mills and SAG mill requiring specialty lubricant. Current product not rated for tropical humidity.', useCase: 'ball mill SAG mill lubrication gold processing tropical humidity', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },

    // General Industrial — Active (15 general opportunities total)
    { id: 'opp-45', accountId: 'acc-19', assignedUserId: 'u-02', stageId: 'stg-4', primaryProductId: 'p-b01', name: 'Krakatau Steel Boiler Chemical Program', value: 2500000000, currency: 'IDR', closeDate: '2026-04-30', problemStatement: 'Steel mill boilers critical for process steam. Current Nalco program expensive and underperforming on silica scale. Looking to switch.', competitorNotes: 'Incumbent: Nalco/Ecolab. Contract expires end of April.', useCase: 'boiler chemical steel mill process steam silica scale', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-46', accountId: 'acc-19', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-ct01', name: 'Krakatau Steel Cooling Tower Program', value: 1800000000, currency: 'IDR', closeDate: '2026-06-15', problemStatement: 'Tropical heat causing severe algae and Legionella risk in 8 cooling towers. Current biocide program inadequate for tropical conditions.', useCase: 'cooling tower biocide algae Legionella steel mill tropical', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-47', accountId: 'acc-20', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-b08', name: 'Indofood Factory Boiler Treatment — Multi-site', value: 1500000000, currency: 'IDR', closeDate: '2026-07-01', problemStatement: 'Standardizing boiler treatment across 12 noodle and food processing factories. Fire tube boilers need all-in-one solution.', useCase: 'boiler treatment food processing factory fire tube multi-site', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-48', accountId: 'acc-21', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-b08', name: 'Wilmar Palm Oil Mill Boiler Program', value: 3200000000, currency: 'IDR', closeDate: '2026-05-30', problemStatement: 'Palm oil mills across Kalimantan and Sumatera with 45 fire tube boilers. Need simplified all-in-one treatment for remote mill operators.', useCase: 'palm oil mill boiler fire tube all-in-one treatment remote site', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-49', accountId: 'acc-22', assignedUserId: 'u-02', stageId: 'stg-4', primaryProductId: 'p-ct06', name: 'Chandra Asri Cooling Water Corrosion Program', value: 2800000000, currency: 'IDR', closeDate: '2026-05-15', problemStatement: 'Ethylene cracker cooling water system corroding heat exchangers. Urgent — corrosion rate exceeding 5 mpy on mild steel.', useCase: 'cooling water corrosion inhibitor petrochemical ethylene cracker', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-50', accountId: 'acc-23', assignedUserId: 'u-03', stageId: 'stg-3', primaryProductId: 'p-lu03', name: 'Semen Indonesia Kiln Gear Lubrication', value: 1400000000, currency: 'IDR', closeDate: '2026-06-30', problemStatement: 'Rotary kiln open gear drives at 4 cement plants need specialty lubrication. Current product not performing in high-temperature and dusty conditions.', useCase: 'kiln open gear lubricant cement plant high temperature dust', isStalled: false, stalledDays: 0, riskLevel: 'medium' as const },
    { id: 'opp-51', accountId: 'acc-23', assignedUserId: 'u-03', stageId: 'stg-5', primaryProductId: 'p-b05', name: 'Semen Indonesia Power Plant Boiler Treatment', value: 850000000, currency: 'IDR', closeDate: '2026-04-22', problemStatement: 'Captive power plant boiler oxygen scavenger supply renewal. 3-year contract.', useCase: 'power plant boiler oxygen scavenger cement captive', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-52', accountId: 'acc-24', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-cl06', name: 'Unilever Production Line Passivation', value: 480000000, currency: 'IDR', closeDate: '2026-08-30', problemStatement: 'New production lines at Cikarang factory need stainless steel passivation and ongoing cleaning chemical supply.', useCase: 'stainless steel passivation cleaning FMCG production line', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-53', accountId: 'acc-25', assignedUserId: 'u-02', stageId: 'stg-1', primaryProductId: 'p-ct01', name: 'Astra Manufacturing Cooling Tower Treatment', value: 950000000, currency: 'IDR', closeDate: '2026-09-30', problemStatement: 'Automotive manufacturing plants with cooling tower Legionella risk. New Disnaker regulation requiring documented treatment program.', useCase: 'cooling tower Legionella automotive manufacturing regulation', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    // General Industrial — STALLED
    { id: 'opp-54', accountId: 'acc-22', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-b01', name: 'Chandra Asri Boiler Scale Treatment', value: 1200000000, currency: 'IDR', closeDate: '2026-05-01', problemStatement: 'Boiler scale treatment proposal submitted. Plant turnaround rescheduled twice. Engineering team focused on cracker issues.', useCase: 'boiler scale petrochemical turnaround delay', isStalled: true, stalledDays: 32, riskLevel: 'high' as const },
    { id: 'opp-55', accountId: 'acc-20', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-ct03', name: 'Indofood Cooling Tower Scale Control', value: 580000000, currency: 'IDR', closeDate: '2026-06-15', problemStatement: 'High-hardness well water causing calcium scale in cooling towers. Proposal submitted but factory engineering manager transferred.', useCase: 'cooling tower scale food factory high hardness well water', isStalled: true, stalledDays: 15, riskLevel: 'medium' as const },
    { id: 'opp-56', accountId: 'acc-25', assignedUserId: 'u-02', stageId: 'stg-2', primaryProductId: 'p-lu02', name: 'Astra Heavy Equipment Workshop Lubrication', value: 320000000, currency: 'IDR', closeDate: '2026-07-31', problemStatement: 'Workshop and service center lubrication supply. Competing against existing Astra Otoparts internal supply chain.', competitorNotes: 'Internal competitor: Astra Otoparts (Shell distributor). Hard to displace.', useCase: 'workshop lubrication heavy equipment service center', isStalled: true, stalledDays: 18, riskLevel: 'high' as const },
    // Additional general active
    { id: 'opp-57', accountId: 'acc-21', assignedUserId: 'u-02', stageId: 'stg-5', primaryProductId: 'p-ct02', name: 'Wilmar Refinery Cooling Tower Algaecide', value: 650000000, currency: 'IDR', closeDate: '2026-04-10', problemStatement: 'Palm oil refinery cooling towers with severe tropical algae problem. EonLine AG 5770 trial successful — PO imminent.', useCase: 'cooling tower algaecide palm oil refinery tropical', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-58', accountId: 'acc-19', assignedUserId: 'u-02', stageId: 'stg-1', primaryProductId: 'p-b03', name: 'Krakatau Steel Annual Boiler Descaling', value: 280000000, currency: 'IDR', closeDate: '2026-10-01', problemStatement: 'Annual shutdown boiler descaling service. Previous year we supplied EonDescaler B 2550 — looking to secure repeat order.', useCase: 'boiler descaling annual shutdown steel mill repeat order', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-59', accountId: 'acc-24', assignedUserId: 'u-02', stageId: 'stg-3', primaryProductId: 'p-cl08', name: 'Unilever HVAC Coil Cleaning Program', value: 350000000, currency: 'IDR', closeDate: '2026-06-20', problemStatement: 'Factory HVAC systems losing efficiency due to tropical dust and humidity on evaporator coils. Need regular cleaning program.', useCase: 'HVAC coil cleaning factory tropical dust humidity', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
    { id: 'opp-60', accountId: 'acc-23', assignedUserId: 'u-03', stageId: 'stg-2', primaryProductId: 'p-b04', name: 'Semen Indonesia Heat Exchanger Descaling', value: 190000000, currency: 'IDR', closeDate: '2026-07-15', problemStatement: 'Waste heat recovery system heat exchangers fouled with calcium and cement dust scale. Descaling needed during quarterly maintenance.', useCase: 'heat exchanger descaling cement waste heat recovery', isStalled: false, stalledDays: 0, riskLevel: 'low' as const },
  ];
  for (const r of opps) await db.insert(schema.opportunities).values(r).onConflictDoNothing();

  // ── Activities ──────────────────────────────────────────────────────────────
  const activities = [
    { id: 'act-01', opportunityId: 'opp-01', accountId: 'acc-01', userId: 'u-02', type: 'site_visit' as const, subject: 'Tanjung Priok wharf condition survey', description: 'Walked Berth 1-3 with Pelindo asset manager Pak Hendra. Documented coating failure areas with photos. Severe tropical delamination on north-facing structures.', outcome: 'Pelindo requesting formal quotation with detailed scope of work', activityDate: '2026-03-15', durationMinutes: 240 },
    { id: 'act-02', opportunityId: 'opp-02', accountId: 'acc-01', userId: 'u-02', type: 'proposal' as const, subject: 'Oil spill response kit proposal — 4 regional ports', description: 'Submitted comprehensive proposal for EonSpill 500 dispersant stockpile and EonKit SP 900 response kits across Tanjung Priok, Tanjung Perak, Makassar, and Belawan.', outcome: 'Under review by Pelindo procurement. Decision expected within 3 weeks.', activityDate: '2026-03-25', durationMinutes: 60 },
    { id: 'act-03', opportunityId: 'opp-08', accountId: 'acc-06', userId: 'u-03', type: 'meeting' as const, subject: 'PAL Indonesia anti-fouling paint technical presentation', description: 'Presented EonFilm 300 self-polishing technology to PAL engineering division. Compared performance vs Chugoku Paints on 36-month interval basis.', outcome: 'Technical team impressed. Requesting trial on next drydock vessel.', activityDate: '2026-03-20', durationMinutes: 120 },
    { id: 'act-04', opportunityId: 'opp-11', accountId: 'acc-09', userId: 'u-02', type: 'call' as const, subject: 'Soechi Lines tank cleaning contract negotiation', description: 'Discussed pricing and delivery terms with procurement Ibu Ratna. They need 24/7 delivery capability for unscheduled tank cleaning.', outcome: 'Agreed on pricing. Final contract terms being drafted by legal.', activityDate: '2026-03-28', durationMinutes: 45 },
    { id: 'act-05', opportunityId: 'opp-13', accountId: 'acc-03', userId: 'u-02', type: 'email' as const, subject: 'Follow-up: Anti-fouling proposal for Djakarta Lloyd', description: 'Sent follow-up email regarding EonFilm 300 proposal submitted 4 weeks ago. Drydock scheduling at Batam shipyard still uncertain.', outcome: 'Reply received — drydock postponed to Q3 due to monsoon season backlog', activityDate: '2026-03-10', durationMinutes: 15 },
    { id: 'act-06', opportunityId: 'opp-26', accountId: 'acc-11', userId: 'u-04', type: 'site_visit' as const, subject: 'Adaro stockpile area inspection — new expansion site', description: 'Visited new 500-hectare stockpile area at Tutupan mine with environmental team. Demonstrated CoalGuard 810 application method with spray truck.', outcome: 'Environmental manager approved product. Awaiting procurement PO.', activityDate: '2026-03-22', durationMinutes: 360 },
    { id: 'act-07', opportunityId: 'opp-29', accountId: 'acc-13', userId: 'u-05', type: 'meeting' as const, subject: 'Freeport pipeline coating technical review', description: 'Met with Freeport engineering team in Timika. Reviewed EonPipe 620 abrasion test results vs competing products. Discussed highland Papua installation challenges.', outcome: 'Shortlisted to final 2 suppliers. Awaiting field trial approval.', activityDate: '2026-03-18', durationMinutes: 180 },
    { id: 'act-08', opportunityId: 'opp-31', accountId: 'acc-14', userId: 'u-05', type: 'demo' as const, subject: 'Vale boiler chemical jar test demonstration', description: 'Conducted jar test at Sorowako site lab comparing EonScale B 5155 vs current Nalco product. Our product showed 40% better scale inhibition at half the dosage.', outcome: 'Site chemist recommending switch. Escalating to procurement.', activityDate: '2026-03-12', durationMinutes: 240 },
    { id: 'act-09', opportunityId: 'opp-45', accountId: 'acc-19', userId: 'u-02', type: 'proposal' as const, subject: 'Krakatau Steel boiler chemical program — formal tender response', description: 'Submitted complete tender response for 2-year boiler chemical supply including EonScale B 5155, EonOxy B 3200, and EonDescaler B 2550.', outcome: 'Shortlisted. Presentation to procurement committee scheduled April 15.', activityDate: '2026-03-30', durationMinutes: 90 },
    { id: 'act-10', opportunityId: 'opp-48', accountId: 'acc-21', userId: 'u-02', type: 'site_visit' as const, subject: 'Wilmar palm oil mill boiler survey — Kalimantan', description: 'Visited 3 palm oil mills in Central Kalimantan. Assessed boiler conditions and water quality. Remote locations make simplified treatment essential.', outcome: 'Confirmed EonGuard B 6000 as ideal product. Sending proposal for 45-unit program.', activityDate: '2026-03-08', durationMinutes: 480 },
    { id: 'act-11', opportunityId: 'opp-37', accountId: 'acc-12', userId: 'u-03', type: 'email' as const, subject: 'Bukit Asam dust suppression — follow up on stalled trial', description: 'Contacted new procurement head Pak Darmawan. Previous contact Pak Agus has been transferred to Ombilin mine.', outcome: 'New procurement head reviewing all pending vendor proposals. Timeline unknown.', activityDate: '2026-03-05', durationMinutes: 20 },
    { id: 'act-12', opportunityId: 'opp-32', accountId: 'acc-15', userId: 'u-04', type: 'meeting' as const, subject: 'KPC stockpile management — insurance requirement discussion', description: 'Met with KPC risk management and insurance broker from Willis Towers Watson. Insurance premium increase of 15% unless coal spontaneous combustion risk mitigated.', outcome: 'KPC fast-tracking CoalGuard 810 purchase. PO expected within 2 weeks.', activityDate: '2026-03-26', durationMinutes: 120 },
    { id: 'act-13', opportunityId: 'opp-49', accountId: 'acc-22', userId: 'u-02', type: 'demo' as const, subject: 'Chandra Asri cooling water corrosion coupon results', description: 'Presented 90-day corrosion coupon test results. EonCor CT 3300 achieved 1.2 mpy vs current 5.3 mpy. Dramatic improvement.', outcome: 'Engineering manager giving verbal approval. Waiting for formal PO.', activityDate: '2026-03-20', durationMinutes: 90 },
    { id: 'act-14', opportunityId: 'opp-50', accountId: 'acc-23', userId: 'u-03', type: 'sample_sent' as const, subject: 'EonRom 200 sample to Semen Indonesia Gresik plant', description: 'Sent 50kg sample drum of EonRom 200 open gear lube for kiln #3 trial. Included application instructions in Bahasa Indonesia for operators.', outcome: 'Trial scheduled for April plant maintenance window', activityDate: '2026-03-15', durationMinutes: 30 },
    { id: 'act-15', opportunityId: 'opp-22', accountId: 'acc-02', userId: 'u-02', type: 'quote' as const, subject: 'Pertamina tanker anti-fouling paint quotation — 6 vessels', description: 'Submitted formal quotation for EonFilm 300 anti-fouling paint for 6 tanker hulls during Singapore drydock. Competitive pricing vs International Paints.', outcome: 'PO received. Delivery to Singapore drydock confirmed for April.', activityDate: '2026-04-01', durationMinutes: 45 },
    { id: 'act-16', opportunityId: 'opp-39', accountId: 'acc-14', userId: 'u-05', type: 'call' as const, subject: 'Vale pipeline project status check', description: 'Called Vale procurement Pak Eko. CAPEX freeze still in effect due to low nickel prices. Project remains on hold but technically approved.', outcome: 'Will resume when nickel price exceeds $18,000/ton. Currently at $16,500.', activityDate: '2026-03-28', durationMinutes: 20 },
  ];
  for (const r of activities) await db.insert(schema.activities).values(r).onConflictDoNothing();

  // ── Notes ────────────────────────────────────────────────────────────────────
  const notesData = [
    { id: 'n-01', opportunityId: 'opp-01', accountId: 'acc-01', userId: 'u-02', content: 'Pak Hendra (Asset Manager) is the key decision maker for Pelindo coating projects. He has authority up to Rp 5B. Above that needs Direksi approval. Very technical — appreciates detailed scope documents.', isPinned: true },
    { id: 'n-02', opportunityId: 'opp-08', accountId: 'acc-06', userId: 'u-03', content: 'PAL Indonesia currently uses Chugoku Marine Paints for anti-fouling. Chugoku announcing 20% price increase effective July. This is our window. Key contact: Pak Bambang (Head of Coating Division).', isPinned: true },
    { id: 'n-03', opportunityId: 'opp-13', accountId: 'acc-03', userId: 'u-02', content: 'Djakarta Lloyd deal stalled due to monsoon season drydock scheduling backlog at Batam shipyard. All available drydock slots taken until September. Need to monitor schedule and be ready when slot opens.', isPinned: true },
    { id: 'n-04', opportunityId: 'opp-14', accountId: 'acc-04', userId: 'u-03', content: 'ASDP is a BUMN — budget approval process goes through Ministry of Transportation. Ibu Kartini (Procurement) says budget approved but disbursement delayed. Typical BUMN procurement timeline: 3-6 months after technical approval.', isPinned: true },
    { id: 'n-05', opportunityId: 'opp-26', accountId: 'acc-11', userId: 'u-04', content: 'Adaro is our biggest mining account. Competitor Nalco/Ecolab is trying to enter with coal dust suppressant. Our advantage: CoalGuard 810 has 5-year track record at Adaro vs untested Nalco product. Emphasize reliability and local stock at Banjarmasin warehouse.', isPinned: true },
    { id: 'n-06', opportunityId: 'opp-29', accountId: 'acc-13', userId: 'u-05', content: 'Freeport pipeline project is high value but complex logistics. Products must be transported by road from Timika to highland mine site at 4,000m elevation. Need to factor in transportation cost and highland temperature performance in proposal.', isPinned: true },
    { id: 'n-07', opportunityId: 'opp-31', accountId: 'acc-14', userId: 'u-05', content: 'Vale Sorowako site currently using Nalco for boiler treatment. Our jar test results are significantly better. Key champion is site chemist Ibu Dewi — she is pushing for the switch internally. Need to support her with detailed technical comparison report.', isPinned: true },
    { id: 'n-08', opportunityId: 'opp-39', accountId: 'acc-14', userId: 'u-05', content: 'Vale pipeline project on hold due to low nickel prices and CAPEX freeze. Do NOT push aggressively — maintain relationship. When nickel prices recover, this will be fast-tracked. Monitor LME nickel price weekly.', isPinned: false },
    { id: 'n-09', opportunityId: 'opp-45', accountId: 'acc-19', userId: 'u-02', content: 'Krakatau Steel Nalco contract expiring end of April. They are frustrated with Nalco service — missed 3 deliveries in last quarter. Our Cilegon branch is 15 minutes from the plant. Emphasize local stock and rapid response in presentation.', isPinned: true },
    { id: 'n-10', opportunityId: 'opp-48', accountId: 'acc-21', userId: 'u-02', content: 'Wilmar palm oil mills are in remote Kalimantan locations. Most mill operators have limited chemistry knowledge. EonGuard B 6000 all-in-one product is ideal — simple dosing, no complex program. Include Bahasa Indonesia dosing guides with large font and pictures.', isPinned: true },
    { id: 'n-11', accountId: 'acc-01', userId: 'u-02', content: 'Pelindo merger (previously Pelindo I-IV) creates opportunity for national supply contract. Previously we only supplied Pelindo II (Jakarta). Now can pitch to consolidated procurement for all ports. Flag to Pak Budi for strategic account planning.', isPinned: false },
    { id: 'n-12', accountId: 'acc-11', userId: 'u-04', content: 'Adaro announcing new mine site at Laung Mining area. Construction starts Q4 2026. All chemical needs for new site need to be quoted by Q3. This could double our Adaro revenue. Start engaging with project team now.', isPinned: false },
    { id: 'n-13', accountId: 'acc-13', userId: 'u-05', content: 'Freeport smelter in Gresik under construction. When operational (est. 2027), will need massive boiler and cooling chemical programs. Monitor construction progress and start building relationships with smelter project team.', isPinned: false },
    { id: 'n-14', opportunityId: 'opp-32', accountId: 'acc-15', userId: 'u-04', content: 'KPC insurance company (Willis Towers Watson) is driving urgency for coal stockpile treatment. This is unusual — normally mining procurement is slow. Use insurance requirement as leverage for faster PO. Reference insurance premium savings in proposal.', isPinned: true },
    { id: 'n-15', accountId: 'acc-25', userId: 'u-02', content: 'Astra International is complex — many subsidiaries (United Tractors, Astra Otoparts, Honda). Each has own procurement. Shell has strong relationship via Astra Otoparts. Enter via United Tractors mining equipment division where we have no incumbent competitor.', isPinned: false },
    { id: 'n-16', opportunityId: 'opp-54', accountId: 'acc-22', userId: 'u-02', content: 'Chandra Asri plant turnaround rescheduled from March to June. Engineering team fully occupied with ethylene cracker maintenance issues. Boiler treatment proposal sitting with engineering Pak Surya who is currently unavailable. Follow up after turnaround in July.', isPinned: false },
  ];
  for (const r of notesData) await db.insert(schema.notes).values(r).onConflictDoNothing();

  console.log('Seed complete ✓');
  console.log(`  Industries:   ${industries.length}`);
  console.log(`  Families:     ${families.length}`);
  console.log(`  Products:     ${products.length}`);
  console.log(`  PIF rows:     ${pif.length}`);
  console.log(`  Users:        ${users.length}`);
  console.log(`  Accounts:     ${accounts.length}`);
  console.log(`  History:      ${history.length}`);
  console.log(`  Stages:       ${stages.length}`);
  console.log(`  Opps:         ${opps.length}`);
  console.log(`  Activities:   ${activities.length}`);
  console.log(`  Notes:        ${notesData.length}`);
  sqlite.close();
}

seed().catch((e) => { console.error(e); process.exit(1); });
